<?php

namespace Redbubble\HtmlBuilder;

use Redbubble\Domain\Page;

abstract class AbstractPageBuilder
{
    protected $page;

    protected $dir;

    public function __construct(Page $page, $dir)
    {
        $this->page = $page;
        $this->dir = rtrim($dir, '/') . '/'; // make sure the dir name ends with a single slash
    }

    /**
     * Up to the subclass to decide which template they want to use to render the Page object
     *
     * @return AbstractTemplate an instance of subclass of AbstractTemplate
     */
    abstract public function getTemplate();

    /**
     * Return the content generated by the template class
     *
     * @return string
     */
    public function createHtml()
    {
        return $this->getTemplate()->render($this->page);
    }

    /**
     * Output the content to a file
     *
     * @return void
     */
    public function output()
    {
        $fileName = $this->page->getTitle() . '.html';
        file_put_contents($fileName, $this->createHtml());
        rename($fileName, $this->dir . $fileName);
    }
}